name: myprayerbook

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/app_content.json

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  